Kick refactor
ghamry03/ft_irc pull request #7
Opened 2023-08-19 23:07 UTC by ghamry03

### Finished implementing KICK command.

#### Notes:
- Implementing KICK command needed a few changes in the existing code to
keep it clean, The new changes shouldn't effect how the rest of the code
works.
- A new numeric reply `ERR_MULITPLEPARAMS` that doesn't exist in RFC2119 protocol was added,
it uses `ERR_UNKNOWNERROR (400)` to let the client know that the server
doesn't support having multiple targets.
- This version of code isn't tested yet since the command was implemented
before the JOIN command was added to the code.

#### Changes:
- Reimplemented KICK command to match the new version of the code.
- KICK command doesn't support multiple targets anymore.
- Added the new system to send numeric replies back to the client, where all the replies are saved in the `replies.hpp` file
- Added a utils namespace that has common utils functions and used them in the existing code.
- Added `getOrigin()` method to `AClient` class to make constructing
      messages easier.

2023-08-21 13:44 UTC, karimomino requested changes
Please resolve all comments requested and resend the review again.

2023-08-21 13:44 UTC, karimomino commented on includes/Replies.hpp
Are we keeping this one or the other one "replies.hpp"

2023-08-21 13:44 UTC, karimomino commented on includes/replies.hpp
Are we keeping this one or the other one "Replies.hpp"

2023-08-21 13:44 UTC, karimomino commented on src/AClient.cpp
> +    std::string const origin = ":" + getNick() + "!" + getUser() + "@" + getIp() + " ";
why are we adding a space at the end? this should be trimmed to prevent problems in the future, we will add spaces when needed at the time of usage.

2023-08-21 13:44 UTC, karimomino commented on src/Commands/Kick.cpp
This needs to be reworked to make it cleaner, this is not why the PR is change requested!

2023-08-21 13:44 UTC, karimomino commented on src/Server.cpp
> +    for ( ; it != _clients.end(); it++ ) {
initialize your `it` variable similar to this
``` C++
for (it = _clients.begin() ; it != _clients.end(); it++ ) {
```

2023-08-21 13:44 UTC, karimomino commented on src/main.cpp
> +        // IRCserver( atoi( av[1] ) , av[2] );
Uncomment this line, it is required to run the server

2023-08-21 13:44 UTC, karimomino commented on src/utils.cpp
do we need to trim inside the split?

2023-08-21 15:25 UTC, ghamry03 commented on includes/replies.hpp
we're keeping `replies.hpp`. there was an issue on my end that caused this. I'll fix it in the next commit.

2023-08-22 14:14 UTC, ghamry03 commented on src/utils.cpp
yes, this version of split doesn't skip the delimiter.

2023-08-23 17:17 UTC, karimomino approved these changes

2023-08-23 17:17 UTC, karimomino commented on src/Commands/Kick.cpp
> +    const std::vector<std::string>& args = utils::split( _rawCommand, " " );
send rawCommand as an argument, no need to store it in a member variable.

2023-08-23 17:17 UTC, karimomino commented on src/Commands/Kick.cpp
> +    _client = client;
no need to store client in member variable pass it where you need

2023-08-24 15:25 UTC, merged